# Generated by Django 3.1.7 on 2021-02-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingaccount',
            name='account_balance',
            field=models.FloatField(max_length=80, null=True),
        ),
    ]
